config/routes.rb
Rails.application.routes.draw do
  #resources :apis

  get 'apis/news', to: 'apis#index'
  get 'apis/:fecha1/:fecha2', to: 'apis#show'
  post 'apis/tweets', to: 'apis#create'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :tweets do
    post 'like', to: 'tweets#like'
    post 'retweet', to: 'tweets#retweet'
  end

  get '/tweets/hashtag/:name', to:'tweets#hashtags'

  devise_for :users, controllers: {registrations: 'users/registrations'}
  root to: "tweets#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_and_belongs_to_many :tags
  validates :content, presence: true

  scope :tweets_for_me, ->(friends) {where(user_id: friends)}

  delegate :profile_photo, to: :user, prefix: :true

  def add_like(user)
    Like.create(user: user, tweet: self)
  end

  def remove_like(user)
    Like.where(user: user, tweet: self).first.destroy
  end

  def original_tweet
    Tweet.find(self.origin_tweet)
  end

#   after_create do
#     hashtags = self.content.scan(/#\w+/)
#     hashtags.uniq.map do |hashtag|
#       tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
#       self.tags << tag 
#     end
#   end

#   before_update do
#     tweet.tags.clear
#     hashtags = self.content.scan(/#\w+/)
#     hashtags.uniq.map do |hashtag|
#       tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
#       self.tags << tag 
#     end
#   end
# end


after_create do
  tweet = Tweet.find_by(id: self.id)
  hastags = self.content.scan(/#\w+/)
  hastags.uniq.map do |hashtag|
      tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
      tweet.tags << tag
  end
end

after_update do
    tweet = Tweet.find_by(id: self.id)
    tweet.tags.clear
    hastags = self.content.scan(/#\w+/)
    hastags.uniq.map do |hashtag|
        tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
        tweet.tags << tag
    end
end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :index
  # respond_to :js, :html, :json
  # GET /tweets
  # GET /tweets.json

  def index
    if params[:content].present?
      @tweets = Tweet.where('content = ?', params[:content])
    else
      @tweets = Tweet.all
    end

    @paginated_tweets = Tweet.page(params[:page]).paginate(page: params[:page], per_page: 50)
  end

  def like
    if current_user
      @tweet = Tweet.find(params[:tweet_id])
      if is_liked?
        @tweet.remove_like(current_user)
      else
        @tweet.add_like(current_user)
      end
    else
      redirect_to new_user_session_path
    end
    redirect_to root_path
  end

  def retweet
    if current_user
      @tweet = Tweet.find(params[:tweet_id])
      Tweet.create(content: @tweet.content , user_id: current_user.id, origin_tweet: @tweet.id)
    else
      redirect_to new_user_session_path
    end
    redirect_to root_path
  end

  def hashtags
    tag = Tag.find_by(name: params[:name])
    @tweets = tag.tweets
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
    @users = User.pluck :profile_photo, :id
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params.merge(user: current_user))
    @tweet.user_id = current_user.id
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    if @tweet.user.id == current_user.id
      respond_to do |format|
        if @tweet.update(tweet_params)
          format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
          format.json { render :show, status: :ok, location: @tweet }
        else
          format.html { render :edit }
          format.json { render json: @tweet.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to tweets_path, notice: 'Only admins or the user who created the story can update'
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def is_liked?
      Like.where(user: current_user.id, tweet: params[:tweet_id]).exists?
    end
    
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content, :user_id, :origin_tweet, :user)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
    def render_with_hashtags(content)
        content.gsub(/#\w+/){|word| link_to word, "/tweets/hashtag/#{word.downcase.delete('#')}"}.html_safe
    end
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <!--      
  
            <div class="field">
              <%= form.label :user_id %>
              <%= form.text_field :user_id %>
            </div>

            <div class="field">
              <%= form.label :origin_tweet %>
              <%= form.number_field :origin_tweet %>
            </div>

  -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/hashtags.html.erb
<h1>LIsting Tweets</h1>

<table>
    <thead>
        <tr>
            <th>Content</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @tweets.each do |tweet| %>
        <tr>
            <td><%= render_with_hashtags(tweet.content) %></td>
        </tr>
    </tbody>

</table>

app/views/tweets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
      <h2>Tweets</h2>
      <% if current_user %>
          <h2 class="text-primary">
            <%= flash[:alert] = "Bienvenido" %>
          </h2>
        <%= link_to 'Create a New Tweet', new_tweet_path, class: "btn btn-info btn-sm" %>
      <% end %>
    </div>
  </div>
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search"
    aria-label="Search" name="content">
    <button class="btn btn-outline-success my-2 my-sm-0"
    type="submit">Search</button>
  </form>
</div>

<br>

<div class="row">
  <% @tweets.reverse.each do |tweet| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= image_tag(tweet.user.profile_picture, width: "40%") %> dice:
        <div class="caption">
          <% if tweet.origin_tweet.nil? %>
            <h3><%= tweet.content %></h3>
          <% else %>
            <%#= image_tag(tweet.origin_tweet.user.profile_picture, width: "20%") %> <%#= tweet.origin_tweet.user.user_name %> dice: 
            <div class="container mx-auto">
              <%= tweet.content %>
            </div>
          <% end %>
          <small><%= time_ago_in_words(tweet.created_at) %> ago</small>
            <p><%= link_to 'Show', tweet, class: "btn btn-primary" %>
              <% if current_user&.id == tweet.user_id %>
                <%= link_to 'Edit', edit_tweet_path(tweet), class: "btn btn-warning" %> 
                <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></p>
              <% end %>
            <br>
            <%= link_to 'Like', tweet_like_path(tweet), method: :post %> <%= tweet.likes.count %>
            <br>
            <%= link_to 'Retweet', tweet_retweet_path(tweet), method: :post %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<br>
  <%#= will_paginate @paginated_tweets, :previous_label => '', :next_label => 'Mostrar más tweets' %>
<br>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @tweet.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user_id %>
</p>

<!-- 
<p>
  <strong>Origin tweet:</strong>
  <%= @tweet.origin_tweet %>
</p>
-->

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>