config/routes.rb
Rails.application.routes.draw do
  #resources :apis

  get 'apis/news', to: 'apis#index'
  get 'apis/:fecha1/:fecha2', to: 'apis#show'
  post 'apis/tweets', to: 'apis#create'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :tweets do
    post 'like', to: 'tweets#like'
    post 'retweet', to: 'tweets#retweet'
  end

  get '/tweets/hashtag/:name', to:'tweets#hashtags'

  devise_for :users, controllers: {registrations: 'users/registrations'}
  root to: "tweets#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/api.rb
class Api < ApplicationRecord
end

app/controllers/apis_controller.rb
class ApisController < InheritedResources::Base

#   include ActionController::HttpAuthentication::Basic::ControllerMethods 
#         http_basic_authenticate_with name: "hello", password: "world", except: :index
#         before_action :set_tweet, only: [:show, :update, :destroy]
#         skip_before_action :verify_authenticity_token

#         respond_to :json

#         def index
#             @tweet = Tweet.last(50).map do |t|
#                 {
#                     id: t.id,
#                     content: t.content,
#                     user_id: t.user_id,
#                     like_count: t.likes.count,
#                     retweets_count: t.origin_tweet
#                 }
#             end
#             render json: @tweet
#         end

#         def show
#             respond_with Tweet.find(params[:id])
#         end

#         def create
#             @tweet = Tweet.new(tweet_params)
            
#             if @tweet.save
#               render json: @tweet
#             else
#               render json: @tweet.errors
#             end
#         end

#         def update
#             respond_with Tweet.update(params[:id], params[:tweet])
#         end

#         def destroy
#             respond_with Tweet.destroy(params[:id])
#         end

#         def between_dates
#             @tweets = Tweet.where(created_at:(params[:fecha1].to_date)..(params[:fecha2].to_date))
#             render json: @tweets
#         end

#         private

#         def set_post
#             @tweet = Tweet.find(params[:id])
#         end

#         def tweet_params
#             params.require(:tweet).permit(:content, :user_id)
#         end

#   # private

#   #   def api_params
#   #     params.require(:api).permit()
#   #   end

# end

protect_from_forgery with: :null_session
# skip_before_action :verify_authenticity_toker
include ActionController::HttpAuthentication::Basic::ControllerMethods
http_basic_authenticate_with name: "hola", password: "mundo"
def index
    # array = []
    # Tweet.all.each do |tweet|
    #     array << {:id => tweet.id, :content => tweet.content, :user_id => tweet.user_id, :likes_count => tweet.likes.count, #:retweets_count => tweet.reposts.count, :retwitted_from => tweet.repost_id} 
    # end
    # @tweets = array
    # render json: @tweets.last(50)
    array = []    
                @tweet = Tweet.last(50).map do |t|
                {
                    :id => t.id,
                    :content => t.content,
                    :user_id => t.user_id,
                    :like_count => t.likes.count,
                    :retweets_count => t.origin_tweet,
                    :retweets_count => t.origin_tweet
                }
            end
            render json: @tweet
end

def show
    @tweets = Tweet.all
    render json: @tweets.where("DATE(created_at) >= :fecha1 AND DATE(created_at) <= :fecha2", {fecha1: params[:fecha1], fecha2: params[:fecha2]})
end

def create
    @tweet = Tweet.new(tweet_params)

    if @tweet.save
        render json: @tweet, status: :created, location: @tweet
    else
        render json: @tweet.errors, status: :unprocessable_entity
    end

            #     @tweet = Tweet.new(tweet_params)
            
            # if @tweet.save
            #   render json: @tweet
            # else
            #   render json: @tweet.errors
            # end
end


private
def tweet_params
    params.require(:tweet).permit(:content, :user_id)
end
end

app/helpers/apis_helper.rb
module ApisHelper
end

app/views/apis/_form.html.erb
<%= form_with(model: api, local: true) do |form| %>
  <% if api.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(api.errors.count, "error") %> prohibited this api from being saved:</h2>

      <ul>
        <% api.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/apis/edit.html.erb
<h1>Editing Api</h1>

<%= render 'form', api: @api %>

<%= link_to 'Show', @api %> |
<%= link_to 'Back', apis_path %>

app/views/apis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apis</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apis.each do |api| %>
      <tr>
        <td><%= link_to 'Show', api %></td>
        <td><%= link_to 'Edit', edit_api_path(api) %></td>
        <td><%= link_to 'Destroy', api, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Api', new_api_path %>

app/views/apis/new.html.erb
<h1>New Api</h1>

<%= render 'form', api: @api %>

<%= link_to 'Back', apis_path %>

app/views/apis/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_api_path(@api) %> |
<%= link_to 'Back', apis_path %>